### ISSUE TITLE
Layer identity not working

### ISSUE THREAD

**Issue by istvanfazakas** [cakejelly/layer-api#17]
Hi,

I am using the layer-api gem to load / create conversations on layer. I was trying to update the users identity using the indications from the readme, but as soon as I tried to call the create_identity method on a retrieved user, I received an error saying: 
```
NoMethodError: undefined method `create_identity' for #<Layer::Resources::User:0xcd73618>
```
Any ideea why is that happening? 
I was testing it very simple:
```
identity = {
  display_name: "Frodo the Dodo",
  avatar_url: "http://sillylordoftheringspictures.com/frodo-riding-a-dodo.png",
  first_name: "Frodo",
  last_name: "Baggins",
  phone_number: "13791379137",
  email_address: "frodo@sillylordoftheringspictures.com",
  metadata: {
    level: "35",
    race: "Dodo"
  }
}
user = @platform.users.find("user_id")
user.create_identity(identity)
```

The gem version I am using is 0.6.1
```
bundle show | grep layer
  * layer-api (0.6.1)
```

**Comment by istvanfazakas** [comment]
Sorry for posting before I tried updating the gem. As I see, it si working with layer-api 0.7.0 (which is not mentioned anywhere).
Just had to update the version, and it was working as expected.

Thanks, and sorry!

**Comment by cakejelly** [comment]
Hey Istvan,

Sorry about that, I add release notes for any new releases (https://github.com/cakejelly/layer-api/releases/tag/v0.7.0) but will look at adding a clearer changelog.

Cheers

**Comment by istvanfazakas** [comment]
Thank you, and sorry for the misunderstanding! 👍
